config/routes.rb
WBlog::Application.routes.draw do

  get 'hello/test'

  resources :blogs, :only=>[:index, :show, :edit] do
    collection do
      get :rss
    end
    resources :comments, only: [:index, :create] do
      collection do
        get :refresh
      end
    end
    resources :likes, only: [:index, :create, :destroy] do
      member do
        get :is_liked
      end
    end
  end


  resources :archives
  resources :subscribes, only: [:index, :new, :create]

  resources :unsubscribes, only: [:index, :new, :create]
  # photos
  resources :photos, only: [:create]
  get '/qrcodes' => 'qrcodes#show'

  namespace :admin do
    resources :posts, except: [:show] do
      collection do
        post :preview
      end
      resources :comments
    end
    resources :sessions, :only=>[:new, :create, :destroy]
    resources :subscribes, only: [:index] do
      member do
        post :enable
        post :disable
      end
    end
    root 'dashboard#index'
  end

  get '/about' => 'home#index'
  get '/mobile' => 'home#mobile'

  root 'blogs#index'

  mount ActionCable.server => '/cable'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates_presence_of :post_id

  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: I18n.t('comment_attributes.email') }
  validates :content, presence: true

  def reply_emails
    Comment.where(post_id: self.post_id).collect(&:email).uniq - [ self.email ] - Subscribe.unsubscribe_list - [ ENV['ADMIN_USER'] ]
  end

  after_commit on: :create do
    if ENV['MAIL_SERVER'].present? && ENV['ADMIN_USER'].present? && ENV['ADMIN_USER'] =~ /@/ && ENV['ADMIN_USER'] != self.email
      Rails.logger.info 'comment created, comment worker start'
      NewCommentWorker.perform_async(self.id.to_s, ENV['ADMIN_USER'])
    end

    if ENV['MAIL_SERVER'].present?
      Rails.logger.info 'comment created, reply worker start'
      NewReplyPostWorker.perform_async(self.id.to_s)
    end
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  layout 'layouts/admin'
  before_action :authericate_user!

  before_action do
    @post = Post.find( params[:post_id] )
  end

  def index
    @comments = @post.comments.order(created_at: :desc)
  end

  def destroy
    comment = @post.comments.find(params[:id])
    if comment.destroy
      flash[:notice] = '删除评论成功'
      redirect_to admin_post_comments_path(@post)
    else
      flash[:alert] = '删除失败'
      redirect_to admin_post_comments_path(@post)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout false

  def index
    @post = Post.find( params[:blog_id] )
    res = @post.comments.desc(:created_at).collect { |comment| build_json(comment) }
    render :json => res
  end

  def create
    unless request.xhr?
      logger.warn "attack action detected: #{params.to_h}"
      redirect_to root_path
      return
    end
    cookies[:name] = comment_params[:name]
    cookies[:email] = comment_params[:email]
    @post = Post.find( params[:blog_id] )
    @comment = @post.comments.build(comment_params)

    if @comment.save
      @comments = @post.comments.order(created_at: :desc)
      ActionCable.server.broadcast "comment_post_#{@comment.post.id}", { not: cookies[:cable_id] }
      render :create_ok
    else
      render :create_fail
    end
  end

  def refresh
    @post = Post.find(params[:blog_id])
    @comments = @post.comments.order(created_at: :desc)
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :name, :email)
  end

  def build_json(comment)
    {
      content: comment.content,
      name: comment.name,
      'created_at' => format_time(comment.created_at)
    }
  end
end

app/views/admin/comments/index.html.slim
.row.admin-posts-field
  .small-12.columns
    h3.blog-title #{t('admin.comments')}
    h4.blog-title
      = link_to @post.title, blog_path(@post), target: '_blank'
    table width="100%"
      thead
        tr
          th #{t('admin.comments_head.name')}
          th #{t('admin.comments_head.email')}
          th #{t('admin.comments_head.content')}
          th #{t('admin.comments_head.created_at')}
          th #{t('admin.comments_head.operation')}
      tbody
        - @comments.each do |comment|
          tr
            td #{comment.name}
            td
              = mail_to comment.email
            td
              = simple_format(comment.content)
            td
              = format_time(comment.created_at)

            td
              = link_to t('admin.comments_head.reply'), blog_path(@post), target: '_blank', class: 'edit-post-link'
              = link_to t('admin.comments_head.destroy'), admin_post_comment_path(@post, comment), method: 'DELETE', 'data-confirm'=> '确认删除?'