config/routes.rb
WBlog::Application.routes.draw do

  get 'hello/test'

  resources :blogs, :only=>[:index, :show, :edit] do
    collection do
      get :rss
    end
    resources :comments, only: [:index, :create] do
      collection do
        get :refresh
      end
    end
    resources :likes, only: [:index, :create, :destroy] do
      member do
        get :is_liked
      end
    end
  end


  resources :archives
  resources :subscribes, only: [:index, :new, :create]

  resources :unsubscribes, only: [:index, :new, :create]
  # photos
  resources :photos, only: [:create]
  get '/qrcodes' => 'qrcodes#show'

  namespace :admin do
    resources :posts, except: [:show] do
      collection do
        post :preview
      end
      resources :comments
    end
    resources :sessions, :only=>[:new, :create, :destroy]
    resources :subscribes, only: [:index] do
      member do
        post :enable
        post :disable
      end
    end
    root 'dashboard#index'
  end

  get '/about' => 'home#index'
  get '/mobile' => 'home#mobile'

  root 'blogs#index'

  mount ActionCable.server => '/cable'
end

app/controllers/blogs_controller.rb
# encoding : utf-8
class BlogsController < ApplicationController

  def index
    @newest = Post.order(created_at: :desc).first
    @recent = Post.order(created_at: :desc).to_a[1..3]
    respond_to do |format|
      format.html
      format.json
    end
  end

  def rss
    @posts = Post.all.order(:created_at => :desc).limit(10)
    render :layout=>false
    response.headers["Content-Type"] = "application/xml; charset=utf-8"
  end

  def show
    cookies[:cable_id] = SecureRandom.uuid
    @post = Post.find(params[:id])
    @post.visited
    @prev = Post.where('created_at < ?', @post.created_at).order(created_at: :desc).first
    @next = Post.where('created_at > ?', @post.created_at).order(created_at: :asc).first
    @comments = @post.comments.order(created_at: :desc)
    @likes_count = @post.likes.count
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
    @post = Post.find( params[:id] )
    redirect_to edit_admin_post_path(@post)
  end
end

app/views/blogs/_comment.html.slim
.row
  .small-12.large-9.large-centered.columns
    = form_for Comment.new, url: blog_comments_path(@post), remote: true do |f|
      .row
        .small-12.large-12.columns
          = f.text_area :content, placeholder: t('comment_placeholder.content')
      .row
        .small-12.large-6.columns
          = f.text_field :name, value: cookies[:name], placeholder: t('comment_placeholder.name')
          = f.text_field :email, value: cookies[:email], placeholder: t('comment_placeholder.email')
      button.button.comment-submit type='submit' data-disable-with=t('comment_placeholder.submitting') #{t('comment_placeholder.submit')}
      #alert-container.alert.callout
        span.text
        button class="close-button" type='button'
          span &times;
    = render partial: 'comments/comment_content', locals: { comments: comments }

app/views/blogs/_post.html.slim
= render partial: 'post_head', locals: { post: post }

.content.markdown
  == post.content_html

p.ptag.published-at
  | #{t('announce_at')}
  span #{format_date(post.created_at)}

= render 'common/copyright'
hr.blog-over
p
  button.button.like-button class="#{'liked' if post.liked_by?(cookies[:like])}" type='button' data-url=blog_likes_path(post)
    span.count #{@likes_count}
    span Like
  .qrcode
    a#qrcode-link href="#"
      i.fi-link
      | #{t('qr_code')}

  .social-share
    .qrcode-wrapper
      = render partial: "qrcode", locals: { str: blog_url(post) }

app/views/blogs/_post_head.html.slim
/ require: locals: { post : post }
h2.blog-title #{post.title}
p.ptag
  span
    i.fi-pricetag-multiple
  span #{post.labels_content}

app/views/blogs/_qrcode.html.slim
.qrcode-image
  #image-tag data-url=str
  p #{t('qrcodetips')}

app/views/blogs/index.html.slim
- if ENV['INTRODUCE'].present?
  - content_for(:meta) do
    meta name="description" content="#{ENV['INTRODUCE'].dup.force_encoding('UTF-8')}"
- content_for(:title) do
  | #{t('title.home')}
.row
  .small-12.large-8.columns
    - unless @newest
      = render 'common/no_blog_here'
    - else
      = render partial: 'post_head', locals: { post: @newest }
      .content.markdown
        == @newest.sub_content

        = link_to t('home.read'), blog_path(@newest), class: 'read-more'
        p.published-at #{t('home.created_at')} #{format_date(@newest.created_at)}

      - if @recent.present?
        h4.recent-title #{t('home.recent')}
        ul.recent-content
          - @recent.each do |re|
            li = link_to re.title,blog_path(re)

  .large-3.columns.large-offset-1.self-introduce.self-introduce-index
    /*Adjust it in common/welcome*/
    = render 'common/welcome'
    h4 #{t('subscribes.title')}
    .row
      .small-12.medium-6.large-12.columns
        ul.subscribe-ul
          - if ENV['ADMIN_USER'].present? && ENV['ADMIN_USER'].include?('@')
            li
              = link_to t('subscribes.email'), new_subscribe_path
          li
            a data-toggle="qrcode-home" #{t('subscribes.wechat') }
            #qrcode-home.weixin-subscribe.hide data-toggler='hide' data-url=root_url
          li
            a data-toggle="rss-home" #{t('subscribes.rss') }
            #rss-home.rss-subscribe.hide data-toggler='hide'
              = link_to rss_blogs_path do
                - image_tag('rss.png')

app/views/blogs/show.html.slim
- content_for(:meta) do
  meta name="description" content=@post.meta_content
  meta name="keywords" content=@post.labels_content

- content_for(:title) do
  | #{@post.title}
.row.blog-wrapper#blog-show-page data-url=refresh_blog_comments_path(@post) data-post_id=@post.id
  .small-12.large-9.large-centered.columns
    = render partial: "post", :locals=> { post: @post }
.comment-field
  = render partial: 'comment', locals: { comments: @comments, post: @post }
  p
  .row
    .small-12.large-9.large-centered.columns
      - if @prev
        = link_to blog_path(@prev), class: 'prev' do
          i.fi-arrow-left
          | Prev
      - if @next
        = link_to blog_path(@next), class: 'next' do
          | Next
          i.fi-arrow-right