config/routes.rb
WBlog::Application.routes.draw do

  get 'hello/test'

  resources :blogs, :only=>[:index, :show, :edit] do
    collection do
      get :rss
    end
    resources :comments, only: [:index, :create] do
      collection do
        get :refresh
      end
    end
    resources :likes, only: [:index, :create, :destroy] do
      member do
        get :is_liked
      end
    end
  end


  resources :archives
  resources :subscribes, only: [:index, :new, :create]

  resources :unsubscribes, only: [:index, :new, :create]
  # photos
  resources :photos, only: [:create]
  get '/qrcodes' => 'qrcodes#show'

  namespace :admin do
    resources :posts, except: [:show] do
      collection do
        post :preview
      end
      resources :comments
    end
    resources :sessions, :only=>[:new, :create, :destroy]
    resources :subscribes, only: [:index] do
      member do
        post :enable
        post :disable
      end
    end
    root 'dashboard#index'
  end

  get '/about' => 'home#index'
  get '/mobile' => 'home#mobile'

  root 'blogs#index'

  mount ActionCable.server => '/cable'
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: '地址无效' }

  def self.subscribe_list
    Subscribe.all.where(enable: true).map(&:email)
  end

  def self.unsubscribe_list
    Subscribe.all.where(enable: false).map(&:email)
  end

  def self.unsubscribe?(email)
    Subscribe.where(email: email, enable: false).first.present?
  end
end

app/controllers/admin/subscribes_controller.rb
class Admin::SubscribesController < ApplicationController
  layout 'layouts/admin'
  before_action :authericate_user!

  def index
    @subscribes = Subscribe.all.order(created_at: :desc).page(params[:page]).per(25)
  end

  def enable
    @subscribe = Subscribe.find(params[:id])

    @subscribe.enable = true
    @subscribe.save!

    redirect_to admin_subscribes_path, notice: "#{@subscribe.email} is enabled!"
  end

  def disable
    @subscribe = Subscribe.find(params[:id])

    @subscribe.enable = false
    @subscribe.save!

    redirect_to admin_subscribes_path, notice: "#{@subscribe.email} is disabled!"
  end
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController

  def index
  end

  def new
    @subscribe = Subscribe.new
  end

  def create
    @subscribe = Subscribe.find_or_initialize_by(email: subscribe_params[:email])
    @subscribe.enable = true

    if @subscribe.save
      redirect_to subscribes_path, notice: '订阅成功'
    else
      render :new
    end
  end

  def subscribe_params
    params.require(:subscribe).permit(:email)
  end

end

app/views/admin/subscribes/index.html.slim
.row.admin-subscribes-field
  .small-12.columns
    h3.blog-title #{t('admin.subscribes') }
    table width="100%"
      thead
        tr
          th #{t('admin.subscribes_head.email')}
          th #{t('admin.subscribes_head.enable')}
          th #{t('admin.subscribes_head.created_at')}
          th #{t('admin.subscribes_head.operation')}
      tbody
        - @subscribes.each do |subscribe|
          tr
            td
              = mail_to subscribe.email
            td
              = subscribe.enable
            td
              = format_time(subscribe.created_at)
            td
              - if subscribe.enable
                = link_to t('admin.subscribes_head.op.disable'), disable_admin_subscribe_path(subscribe), method: 'POST', data: { confirm: 'Confirm?' }
              - else
                = link_to t('admin.subscribes_head.op.enable'), enable_admin_subscribe_path(subscribe), method: 'POST', data: { confirm: 'Confirm?' }
    == paginate @subscribes