config/routes.rb
WBlog::Application.routes.draw do

  get 'hello/test'

  resources :blogs, :only=>[:index, :show, :edit] do
    collection do
      get :rss
    end
    resources :comments, only: [:index, :create] do
      collection do
        get :refresh
      end
    end
    resources :likes, only: [:index, :create, :destroy] do
      member do
        get :is_liked
      end
    end
  end


  resources :archives
  resources :subscribes, only: [:index, :new, :create]

  resources :unsubscribes, only: [:index, :new, :create]
  # photos
  resources :photos, only: [:create]
  get '/qrcodes' => 'qrcodes#show'

  namespace :admin do
    resources :posts, except: [:show] do
      collection do
        post :preview
      end
      resources :comments
    end
    resources :sessions, :only=>[:new, :create, :destroy]
    resources :subscribes, only: [:index] do
      member do
        post :enable
        post :disable
      end
    end
    root 'dashboard#index'
  end

  get '/about' => 'home#index'
  get '/mobile' => 'home#mobile'

  root 'blogs#index'

  mount ActionCable.server => '/cable'
end

app/views/layouts/_footer.html.slim
.row
  .small-12.columns
    .footer
      div
        span.link = ENV['SITE_ADDRESS']
      .license
        | Designed by
        span
          = link_to 'Alice', 'http://zhuwenqian.com/about', target: '_blank'
      .license
        | Built with
        span
          = link_to 'AliceBlog', 'https://github.com/victorialice/AliceBlog', target: '_blank'

app/views/layouts/admin.html.slim
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title Admin Page for #{ENV['SITE_NAME']}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    .title-bar data-responsive-toggle="example-menu" data-hide-for="medium"
      button class="menu-icon" type="button" data-toggle=''
      .title-bar-title Menu

    .top-bar#dashboard-topbar
      .top-bar-left
        ul.menu
          li
            = link_to "Dashboard For #{ENV['SITE_NAME']}", admin_root_path
          li
            = link_to t('admin.new_post'), new_admin_post_path
          li
            = link_to t('admin.posts'), admin_posts_path
          li
            = link_to t('admin.subscribes'), admin_subscribes_path
      .top-bar-right
        ul.menu
          li
            = link_to t('admin.back'), root_path
          - if admin_username
            li
              = link_to admin_username + ' [ ' + t('admin.logout') + ' ]', admin_session_path(1), method: 'DELETE'
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        div class=("callout #{name.to_sym == :notice ? "success" : "alert"}") data-closable=""
          = content_tag :div, msg
          button.close-button type='button' data-close='' &times;
    .admin-main-field ng-app="app"
      = yield
    = render "layouts/footer"

app/views/layouts/application.html.slim
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"
    - if content_for?(:meta)
      = yield(:meta)
    title
      = content_for?(:title) ? yield(:title) + " | #{ENV['SITE_NAME']}" : ENV['SITE_NAME']
    = stylesheet_link_tag "application", 'data-turbolinks-track' => "reload"
    = favicon_link_tag 'favicon.png', type: 'image/png'
    = javascript_include_tag "application", 'data-turbolinks-track' => "reload", 'defer' => true
    = csrf_meta_tags
    = action_cable_meta_tag
  body data-whatinput="mouse"
    - if content_for?(:main)
      = yield(:main)
    - else
      .off-canvas-wrapper
        .off-canvas-wrapper-inner data-off-canvas-wrapper=''
          .off-canvas.position-left id="offCanvas" data-off-canvas=''
            ul.vertical.menu
              li
                label Menu
              li
                = link_to root_path do
                  i.fi-home
                  | #{t('head.home')}
              li
                label Archive
              li
                = link_to archives_path do
                  i.fi-align-justify
                  | #{t('head.timeline')}
              li
                label About
                = link_to about_path do
                  i.fi-torso
                  | #{t('head.about')}
          .off-canvas-content data-off-canvas-content=''
            .title-bar.hide-for-medium.my-topbar
              .title-bar-left
                button.menu-icon type='button' data-open='offCanvas'
                span.title-bar-title
                  = link_to ENV['SITE_NAME'], root_path
            .top-bar.show-for-medium.my-topbar
              .top-bar-left
                ul.dropdown.menu data-dropdown-menu=''
                  li
                    = link_to ENV['SITE_NAME'], root_path, class: 'title'
              .top-bar-right
                ul.dropdown.menu data-dropdown-menu=''
                  li
                    = link_to t('head.home'), root_path
                  li
                    = link_to t('head.timeline'), archives_path
                  li
                    = link_to t('head.about'), about_path
            - flash.each do |name, msg|
              - if msg.is_a?(String)
                div class=("callout #{name.to_sym == :notice ? "success" : "alert"}") data-closable=""
                  = content_tag :div, msg
                  button.close-button type='button' data-close='' &times;
            = render 'common/welcome_new_year'
            = yield
            = render "layouts/footer"